accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import (
    show_private_profile,
    show_public_profile,
)

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('me/', show_private_profile, name='me-profile'),
    path('users/<str:username>/', show_public_profile, name='user-profile'),
]

catsordogs/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic import RedirectView
from django.views.static import serve

import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('profiles/', include('accounts.urls', namespace='accounts')),
    path(
        'notifications/',
        include('notifications.urls', namespace='notifications'),
    ),
    path('polls/', include('polls.urls', namespace='polls')),
    path('shortlinks/', include('shortlinks.urls', namespace='shortlinks')),
    path(
        '',
        RedirectView.as_view(url=reverse_lazy('polls:polls_list')),
        name='index',
    ),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        re_path(
            r'^static/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.STATIC_ROOT,
            },
        ),
    ]

polls/urls.py
from django.urls import path, register_converter

from polls.converters import secret_converter_factory
from polls import views


register_converter(secret_converter_factory(), 'secret')


app_name = 'polls'
urlpatterns = [
    path('', views.poll_list, name='polls_list'),
    path('new/', views.poll_new, name='polls_new'),
    path(
        '<int:poll_pk>/',
        views.poll_description,
        name='polls_details',
    ),
    path(
        'secret/<secret:secret_token>/',
        views.poll_description,
        name='secret_polls_details',
    ),
    path(
        '<int:poll_pk>/vote/<int:choice_pk>/',
        views.poll_choice_vote,
        name='polls_vote',
    ),
    path(
        'secret/<secret:secret_token>/vote/<int:choice_pk>/',
        views.poll_choice_vote,
        name='secret_polls_vote',
    ),
    path(
        '<int:poll_pk>/unvote/<int:choice_pk>/',
        views.poll_choice_unvote,
        name='polls_unvote',
    ),
    path(
        'secret/<secret:secret_token>/unvote/<int:choice_pk>/',
        views.poll_choice_unvote,
        name='secret_polls_unvote',
    ),
    path(
        '<int:poll_pk>/comment/',
        views.poll_comment_new,
        name='polls_comment',
    ),
    path(
        'secret/<secret:secret_token>/comment/',
        views.poll_comment_new,
        name='secret_polls_comment',
    ),
]

polls/models.py
from pathlib import Path

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone

from accounts.models import Account
from catsordogs.utils.models import PrintableModelMixin
from polls.secret_token_utils import generate_secret_token


class ConfidentialityType(models.TextChoices):
    OPEN = 'open', 'Open'
    SECRET = 'secret', 'Secret'


def upload_poll_background_to(poll: 'Poll', filename: str) -> Path:
    return Path(
        'polls',
        'backgrounds',
        generate_secret_token(size=32) + Path(filename).suffix,
    )


def is_secret_token(value: str):
    if value == '' or not all(
        character in settings.POLL_SECRET_KEY_ALPHABET for character in value
    ):
        raise ValidationError(f'Value {value} is not valid secret token')


class PollQuerySet(QuerySet):
    def public_only(self):
        return self.filter(secret_token=None)


class Poll(PrintableModelMixin, models.Model):
    objects = PollQuerySet.as_manager()

    author = models.ForeignKey(
        Account, on_delete=models.PROTECT, related_name='polls'
    )
    title = models.CharField(max_length=128)
    description = models.TextField(verbose_name='Description', blank=True)
    confidentiality_type = models.CharField(
        verbose_name='Confidentiality',
        max_length=32,
        choices=ConfidentialityType.choices,
        default='open',
    )
    multiple_votes = models.BooleanField(
        verbose_name='Multiple votes by one voter', default=False
    )
    can_undo_votes = models.BooleanField(
        verbose_name='Undo votes',
        default=False,
    )
    background_image = models.ImageField(
        verbose_name='Background image',
        upload_to=upload_poll_background_to,
        blank=True,
    )
    is_closed = models.BooleanField(verbose_name='Is closed', default=False)
    secret_token = models.CharField(
        verbose_name='Secret url slug',
        max_length=64,
        validators=[is_secret_token],
        blank=True,
        null=True,
        unique=True,
    )

    def voted_choices_by(self, account: Account) -> 'QuerySet[Choice]':
        return self.choices.filter(voters=account)

    @property
    def is_public(self) -> bool:
        return self.secret_token is None

    @property
    def url_for_view(self) -> str:
        if self.is_public:
            return reverse('polls:polls_details', kwargs={'poll_pk': self.pk})
        else:
            return reverse(
                'polls:secret_polls_details',
                kwargs={'secret_token': self.secret_token},
            )

    @property
    def url_for_comment(self) -> str:
        if self.is_public:
            return reverse('polls:polls_comment', kwargs={'poll_pk': self.pk})
        else:
            return reverse(
                'polls:secret_polls_comment',
                kwargs={'secret_token': self.secret_token},
            )

    def get_absolute_url(self) -> str:
        return self.url_for_view


class PollClosingByTime(PrintableModelMixin, models.Model):
    poll = models.OneToOneField(
        Poll, on_delete=models.CASCADE, related_name='closing_by_time'
    )
    dt_close_after = models.DateTimeField(verbose_name='Close after')

    @property
    def triggered(self):
        return timezone.now() > self.dt_close_after


class PollClosingByVoters(PrintableModelMixin, models.Model):
    poll = models.OneToOneField(
        Poll, on_delete=models.CASCADE, related_name='closing_by_voters'
    )
    count = models.IntegerField(verbose_name='Count of voters')

    @property
    def triggered(self):
        return (
            Account.objects.filter(choices__poll=self.poll).count()
            >= self.count
        )


class PollClosingManual(PrintableModelMixin, models.Model):
    poll = models.OneToOneField(
        Poll, on_delete=models.CASCADE, related_name='closing_manual'
    )
    account_closed = models.ForeignKey(
        Account, on_delete=models.PROTECT, related_name='poll_closings'
    )

    @property
    def triggered(self):
        return True


class Choice(PrintableModelMixin, models.Model):
    title = models.CharField(max_length=128)
    poll = models.ForeignKey(
        Poll, related_name='choices', on_delete=models.CASCADE
    )
    voters = models.ManyToManyField(
        Account, related_name='choices', blank=True
    )

    def is_voted_by(self, account: Account) -> bool:
        return self.voters.filter(pk=account.id).exists()

    def can_be_voted_by(self, account: Account) -> bool:
        if self.poll.is_closed:
            return False
        if self.poll.multiple_votes:
            if self.is_voted_by(account):
                return False
        else:
            if self.poll.voted_choices_by(account).exists():
                return False
        return True

    def can_be_unvoted_by(self, account: Account) -> bool:
        if self.poll.is_closed:
            return False
        if not self.poll.can_undo_votes:
            return False
        return self.is_voted_by(account)

    @property
    def url_for_vote(self):
        if self.poll.is_public:
            return reverse(
                'polls:polls_vote',
                kwargs={'choice_pk': self.pk, 'poll_pk': self.poll.pk},
            )
        else:
            return reverse(
                'polls:secret_polls_vote',
                kwargs={
                    'choice_pk': self.pk,
                    'secret_token': self.poll.secret_token,
                },
            )

    @property
    def url_for_unvote(self):
        if self.poll.is_public:
            return reverse(
                'polls:polls_unvote',
                kwargs={'choice_pk': self.pk, 'poll_pk': self.poll.pk},
            )
        else:
            return reverse(
                'polls:secret_polls_unvote',
                kwargs={
                    'choice_pk': self.pk,
                    'secret_token': self.poll.secret_token,
                },
            )


class Comment(PrintableModelMixin, models.Model):
    author = models.ForeignKey(Account, on_delete=models.PROTECT)
    poll = models.ForeignKey(
        Poll, on_delete=models.CASCADE, related_name='comments'
    )
    content = models.TextField(max_length=256)

polls/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from django.utils import timezone

from polls.models import Choice, Comment, Poll


class PollForm(forms.ModelForm):
    dt_close_after = forms.DateTimeField(
        widget=forms.SelectDateWidget,
        required=False,
        help_text='When the poll must close. Leave empty if no needed.',
    )
    voters_count_close = forms.IntegerField(
        required=False,
        help_text='Max count of voters. Leave empty if no needed.',
    )
    is_public = forms.BooleanField(
        label='Public',
        required=False,
        help_text='Should this poll be accessible by random url.',
        initial=True,
    )

    class Meta:
        model = Poll
        fields = [
            'title',
            'description',
            'multiple_votes',
            'can_undo_votes',
            'confidentiality_type',
            'dt_close_after',
            'voters_count_close',
            'background_image',
            'is_public',
        ]

    def clean_dt_close_after(self):
        dt_close_after = self.cleaned_data['dt_close_after']
        if dt_close_after is not None and dt_close_after <= timezone.now():
            raise ValidationError('Close after date must be a future')
        return dt_close_after

    def clean_voters_count_close(self):
        voters_count_close = self.cleaned_data['voters_count_close']
        if voters_count_close is not None and voters_count_close < 1:
            raise ValidationError('Max voters count must be at least 1')
        return voters_count_close


ChoiceFormset = inlineformset_factory(
    Poll,
    Choice,
    fields=['title'],
    can_delete=False,
    min_num=1,
    validate_min=True,
)


class CommentNewForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

polls/views/poll_choice_unvote.py
from typing import Optional, cast

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect

from catsordogs.errors import NotFoundError
from catsordogs.utils.errors import wrap_exception
from polls import use_cases


@login_required()
@wrap_exception(NotFoundError, Http404)
def poll_choice_unvote(
    request: HttpRequest,
    choice_pk: int,
    poll_pk: Optional[int] = None,
    secret_token: Optional[str] = None,
) -> HttpResponse:
    account_pk = cast(User, request.user).account.pk

    poll = use_cases.unvote_for_choice(
        poll_pk,
        secret_token,
        choice_pk,
        by_account_pk=account_pk,
    )
    return redirect(poll.url_for_view)

polls/views/poll_choice_vote.py
from typing import Optional, cast

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect

from catsordogs.errors import NotFoundError
from catsordogs.utils.errors import wrap_exception
from polls import use_cases


@login_required()
@wrap_exception(NotFoundError, Http404)
def poll_choice_vote(
    request: HttpRequest,
    choice_pk: int,
    poll_pk: Optional[int] = None,
    secret_token: Optional[str] = None,
) -> HttpResponse:
    account_pk = cast(User, request.user).account.pk

    poll = use_cases.vote_for_choice(
        poll_pk,
        secret_token,
        choice_pk,
        by_account_pk=account_pk,
    )
    return redirect(poll.url_for_view)

polls/views/poll_comment_new.py
from typing import cast, Optional

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect
from django.urls import reverse

from catsordogs.errors import NotFoundError
from catsordogs.utils.errors import wrap_exception
from polls import use_cases
from polls.forms import CommentNewForm


@login_required()
@wrap_exception(NotFoundError, Http404)
def poll_comment_new(
    request: HttpRequest,
    poll_pk: Optional[int] = None,
    secret_token: Optional[str] = None,
) -> HttpResponse:
    form = CommentNewForm(request.POST)
    if form.is_valid():
        author_pk = cast(User, request.user).account.pk
        poll_url = use_cases.create_comment(
            poll_pk=poll_pk,
            secret_token=secret_token,
            author_pk=author_pk,
            content=form.cleaned_data['content'],
        )
        return redirect(poll_url)
    return redirect(reverse('polls:polls_new'))

polls/views/poll_description.py
from typing import Optional

from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render

from catsordogs.errors import NotFoundError
from catsordogs.utils.errors import wrap_exception
from polls import use_cases
from polls.forms import CommentNewForm


@wrap_exception(NotFoundError, Http404)
def poll_description(
    request: HttpRequest,
    poll_pk: Optional[int] = None,
    secret_token: Optional[str] = None,
) -> HttpResponse:
    if request.user.is_authenticated:
        account_pk = request.user.account.pk
    else:
        account_pk = None

    return render(
        request,
        'polls/poll.html',
        {
            'poll': use_cases.get_poll_details(
                poll_pk=poll_pk,
                secret_token=secret_token,
                account_pk=account_pk,
            ),
            'comment_form': CommentNewForm(),
        },
    )

polls/views/poll_list.py
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render

from catsordogs.errors import NotFoundError
from catsordogs.utils.errors import wrap_exception
from polls import use_cases


@wrap_exception(NotFoundError, Http404)
def poll_list(
    request: HttpRequest,
) -> HttpResponse:
    return render(
        request,
        'polls/list.html',
        dict(
            polls=use_cases.get_public_polls(),
        ),
    )

polls/views/poll_new.py
from typing import cast

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import (
    HttpRequest,
    HttpResponse,
    Http404,
)
from django.shortcuts import redirect, render

from catsordogs.utils.errors import wrap_exception
from catsordogs.utils.views import view_dispatch
from polls import use_cases
from polls.forms import ChoiceFormset, PollForm


def poll_new_get(request: HttpRequest) -> HttpResponse:
    return render(
        request,
        'polls/new.html',
        context=dict(poll_form=PollForm(), choices_formset=ChoiceFormset()),
    )


@login_required()
@wrap_exception(ValueError, Http404)
def poll_new_post(request: HttpRequest) -> HttpResponse:
    poll_form = PollForm(request.POST, request.FILES)
    choices_formset = ChoiceFormset(request.POST)
    if poll_form.is_valid() and choices_formset.is_valid():  # type: ignore
        author = cast(User, request.user).account
        choices_titles = [
            choice_form.cleaned_data['title']
            for choice_form in choices_formset
            if choice_form.cleaned_data
        ]
        created_poll_url = use_cases.create_poll(
            title=poll_form.cleaned_data['title'],
            description=poll_form.cleaned_data['description'],
            author_pk=author.pk,
            choices_titles=choices_titles,
            allow_multiple_votes=poll_form.cleaned_data['multiple_votes'],
            allow_undo_votes=poll_form.cleaned_data['can_undo_votes'],
            confidentiality_type=poll_form.cleaned_data[
                'confidentiality_type'
            ],
            background_image=poll_form.cleaned_data['background_image'],
            dt_close_after=poll_form.cleaned_data['dt_close_after'],
            max_voters_count=poll_form.cleaned_data['voters_count_close'],
            is_public=poll_form.cleaned_data['is_public'],
        )
        return redirect(created_poll_url)
    else:
        return redirect('polls:polls_new')


poll_new = view_dispatch(
    get_view=poll_new_get,
    post_view=poll_new_post,
)

polls/templates/polls/list.html
{% extends 'base.html' %}

{% block main %}
<div class="container mt-4">
    <h2 class="text-center">Available polls</h2>
    <ul class="list-group">
        {% for poll in polls %}
            <li class="list-group-item">
                <a href="{% url 'polls:polls_details' poll_pk=poll.id %}"><h3>{{ poll.title }}</h3></a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

polls/templates/polls/new.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block main %}
<div class="container mt-4">
    <h2 class="text-center">New poll</h2>
    <form action="{% url 'polls:polls_new' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form poll_form %}
        <div>
            <h3>Choices:</h3>
            {% bootstrap_formset choices_formset %}
        </div>
        {% buttons %}
            <button type="submit" class="btn btn-lg btn-primary">Create a poll</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

polls/templates/polls/poll.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% load markdown_extras %}

{% block main %}
{% if poll.background_image_url %}
    <img class="poll_banner img-fluid poll-banner" src="{{ poll.background_image_url }}" alt="{{ poll.background_image_filename }}">
{% endif %}
<div class="container mt-4">
    <h2>
        {% if poll.is_closed %}<span class="badge badge-warning">Closed</span>{% endif %}
        <a href="{% url 'accounts:user-profile' username=poll.author_username %}">{{ poll.author_username }}</a>:
        {{ poll.title }}
    </h2>

    {% if poll.description %}
        <div>{{ poll.description|render_as_markdown|safe }}</div>
    {% endif %}

    <div class="mt-4 p-3 shadow">
        {% for choice in poll.choices %}
            <div class="card mt-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ choice.title }} <span class="badge badge-warning">({{ choice.voters|length }} voter{{ choice.voters|length|pluralize }})</span></h5>
                    <div style="height: 30px;" class="d-flex">
                        <form class="mr-2" action="{{ choice.url_for_vote }}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-success h-100" type="submit"{% if not choice.can_be_voted %} disabled{% endif %}><i class="gg-math-plus"></i></button>
                        </form>
                        <form action="{{ choice.url_for_unvote }}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-danger h-100" type="submit"{% if not choice.can_be_unvoted %} disabled{% endif %}><i class="gg-math-minus"></i></button>
                        </form>
                    </div>
                    {% if poll.show_voters and choice.voters|length %}
                    <div class="mt-2">
                        <h4>Voters:</h4>
                        <ul class="list-group">
                            {% for voter in choice.voters %}
                                <li class="list-group-item">{{ voter.username }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="mt-4 p-3 shadow">
        {% if user.is_authenticated %}
            <div>
                <h3>New comment</h3>
                <form action="{{ poll.url_for_comment }}" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form comment_form %}
                    {% buttons %}
                        <button class="btn btn-lg btn-primary" type="submit">Comment the poll</button>
                    {% endbuttons %}
                </form>
            </div>
        {% endif %}
        {% if poll.comments|length > 0 %}
            <div class="mt-2">
                <h3>Comments</h3>
                <div>
                    {% for comment in poll.comments %}
                        <div class="card mt-2 shadow-sm" id="comment_{{ comment.pk }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ comment.author_username }} commented:</h5>
                                <p class="card-text">{{ comment.content }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}