accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import (
    show_private_profile,
    show_public_profile,
)

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('me/', show_private_profile, name='me-profile'),
    path('users/<str:username>/', show_public_profile, name='user-profile'),
]

catsordogs/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic import RedirectView
from django.views.static import serve

import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('profiles/', include('accounts.urls', namespace='accounts')),
    path(
        'notifications/',
        include('notifications.urls', namespace='notifications'),
    ),
    path('polls/', include('polls.urls', namespace='polls')),
    path('shortlinks/', include('shortlinks.urls', namespace='shortlinks')),
    path(
        '',
        RedirectView.as_view(url=reverse_lazy('polls:polls_list')),
        name='index',
    ),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        re_path(
            r'^static/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.STATIC_ROOT,
            },
        ),
    ]

notifications/urls.py
from django.urls import path

from notifications.views.notification_mark_as_read import (
    mark_notifications_as_read,
)

app_name = 'notifications'

urlpatterns = [
    path(
        'me/notifications/mark-as-read/',
        mark_notifications_as_read,
        name='notifications-mark-as-read',
    ),
]

polls/urls.py
from django.urls import path, register_converter

from polls.converters import secret_converter_factory
from polls import views


register_converter(secret_converter_factory(), 'secret')


app_name = 'polls'
urlpatterns = [
    path('', views.poll_list, name='polls_list'),
    path('new/', views.poll_new, name='polls_new'),
    path(
        '<int:poll_pk>/',
        views.poll_description,
        name='polls_details',
    ),
    path(
        'secret/<secret:secret_token>/',
        views.poll_description,
        name='secret_polls_details',
    ),
    path(
        '<int:poll_pk>/vote/<int:choice_pk>/',
        views.poll_choice_vote,
        name='polls_vote',
    ),
    path(
        'secret/<secret:secret_token>/vote/<int:choice_pk>/',
        views.poll_choice_vote,
        name='secret_polls_vote',
    ),
    path(
        '<int:poll_pk>/unvote/<int:choice_pk>/',
        views.poll_choice_unvote,
        name='polls_unvote',
    ),
    path(
        'secret/<secret:secret_token>/unvote/<int:choice_pk>/',
        views.poll_choice_unvote,
        name='secret_polls_unvote',
    ),
    path(
        '<int:poll_pk>/comment/',
        views.poll_comment_new,
        name='polls_comment',
    ),
    path(
        'secret/<secret:secret_token>/comment/',
        views.poll_comment_new,
        name='secret_polls_comment',
    ),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import QuerySet
from django.db.models.signals import post_save
from django.dispatch import receiver


class AccountQuerySet(QuerySet):
    def get_by_username(self, username: str) -> 'Account':
        return self.get(user__username=username)


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    objects = AccountQuerySet.as_manager()

    def __str__(self):
        return f'{self.id}# {self.user.username}'


@receiver(post_save, sender=User)
def create_user_account(sender, instance, created, **kwargs):
    if created:
        Account.objects.create(user=instance)

accounts/views/profile.py
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from accounts import use_cases
from catsordogs.errors import NotFoundError
from catsordogs.utils.errors import wrap_exception


@require_GET
@wrap_exception(NotFoundError, Http404)
def show_public_profile(request: HttpRequest, username: str) -> HttpResponse:
    profile_schema = use_cases.show_public_profile(
        of_account_username=username
    )
    return render(
        request, 'accounts/profile.html', context=dict(account=profile_schema)
    )

accounts/views/profile_me.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from accounts import use_cases


@login_required
@require_GET
def show_private_profile(request: HttpRequest) -> HttpResponse:
    username = request.user.username
    profile_schema = use_cases.show_private_profile(
        of_account_username=username
    )
    return render(
        request,
        'accounts/me_profile.html',
        context=dict(account=profile_schema),
    )

accounts/templates/accounts/me_profile.html
{% extends 'base.html' %}

{% block main %}
<div class="container mt-4">
    <h2>Hello {{ account.username }}</h2>

    {% if account.all_polls %}
        <h3>My polls:</h3>
        <ul class="list-group">
        {% for poll in account.all_polls %}
            <li class="list-group-item mt-2 border">
                <a href="{{ poll.url_for_view }}">
                    {% if not poll.is_public %}<span class="text-black-50">(secret)</span>{% endif %}
                    {{ poll.title }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}

    {% if account.unread_notifications %}
    <h3>Unread notifications:</h3>
    <ul class="list-group">
        {% for notification in account.unread_notifications %}
            <li class="d-flex align-items-baseline justify-content-between list-group-item mt-2">
                <div>{{ notification.content }}</div>
                {% if notification.related_url %}
                    <a class="btn btn-outline-primary p-1 rounded" href="{{ notification.related_url }}">
                        See more
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <form action="{% url 'notifications:notifications-mark-as-read' %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-lg btn-primary mt-2" type="submit">Mark as read</button>
    </form>
    {% else %}
    <h3>You have no new notifications</h3>
    {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block main %}
<div class="container mt-4">
    <h2>User {{ account.username }}</h2>

    {% if account.polls %}
        <h3>Polls:</h3>
        <ul class="list-group">
        {% for poll in account.polls %}
            <li class="list-group-item mt-2"><a href="{{ poll.url_for_view }}">{{ poll.title }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}